output_root:  demo/                            # parent folder for models
script:       demo/general_train_nca_to_pde.py

grid:
  PDE: ["ks"]
  TIME_SAMPLING: [32]
  LEARN_RATE:    [5e-4]
  FIRE_RATE:     [1.0]
  STATE_REGULARISER: [1.0]
  LOSS:          ["l1"]